Update 15-equipment-and-supplies.md
sinProject-Inc/sinpro-dev pull request #369
Opened 2024-01-16 12:51 UTC by niki

DeviceにMacBook Pro M3 Proのリンクを登録(本アドレスでない)

closes #368 

# For the Submitter

## Tasks

- [x] Make sure all checkboxes in the Issue content are checked
- [x] Make sure the PR title is in the format `<Issue Title> <Issue Number>`
- [x] Make sure "closes (issue number)" is written close to the top
- [ ] Attach the enhancement label for update tasks
- [ ] Make sure CI completes successfully
- [ ] Check everything written in the PR
- [ ] Fix the issues pointed out by AI
- [x] Add reviewers
- [ ] On Slack, mention the PR reviewer, write your thoughts on the issue, and inform them that the PR has been created

# For the Reviewer

## Checks

- [x] Each task for the related issue are written and in checkboxes
- [ ] The branch name is close to the issue name
- [ ] CI completes successfully
- [ ] Changes include only what is necessary for this PR
- [ ] Necessary unit tests are implemented
- [ ] Necessary E2E tests are implemented
- [ ] Perform functionality checks
- [x] If there are any problems, request revisions from the PR submitter and mention them on Slack

## After Reviewing

- [x] Leave an approval comment (e.g. LGTM)
- [ ] On Slack, mention the PR submitter and a project admin, write which PR you have reviewed, and ask the project admin to review and merge the PR
- [x] If you are a project admin, merge the PR
- [ ] Write an approval comment with praise on Slack

2024-01-18 02:48 UTC, sinproject-iwasaki requested changes
- [ ] Issue は Implement necessary Unit tests と Implement necessary E2E tests を除いたものをすべて実行し、チェックを行う。
- [ ] PR は、For the Reviewer 以下はレビュアーが行うのでチェックは不要です。

2024-01-18 02:48 UTC, sinproject-iwasaki commented on docs/70-team-sinproject/15-equipment-and-supplies.md
> +<a class="flex-equipment" href="https://www.amazon.co.jp/Apple-MacBook-%E3%82%B3%E3%82%A2CPU%E3%80%8118-%E3%82%B3%E3%82%A2GPU-Pro%E3%83%81%E3%83%83%E3%83%97%E6%90%AD%E8%BC%89%E3%83%8E%E3%83%BC%E3%83%
- [ ] 新規追加ではなく、M2の内容を置き換える。
- [ ] 画像リンクではなく、シンプルなテキストリンクにする。（issue ご確認下さい。)

2024-01-23 22:11 UTC, niki commented
PR対応。
チェックボックスの確認。

2024-01-31 04:35 UTC, sinproject-iwasaki approved these changes

2024-01-31 04:37 UTC, merged

2024-01-31 04:42 UTC, sinproject-iwasaki commented
@niki PRありがとうございました。マージを行いました。

今後のために以下、ご確認下さいませ。

- [ ] 下記対応の完了予定をご連絡下さいませ。（今後は予定を確認しませんが随時ご連絡下さいませ。）
- [ ] [Issue](https://github.com/sinProject-Inc/sinpro-dev/issues/368) のチェック項目で、完了しているものにチェックをつけて下さい。
- [ ] PRの指摘項目4箇所にて、確認したものにチェックを付けて下さい。
- [ ] sinpro.dev の [Git Branches and Commits](http://localhost:5173/docs/git-branches-and-commits) に、ブランチの命名規約と、コミットメッセージのルールがありますのでご確認下さいませ。
- [ ] 上記対応完了後にご連絡下さいませ。（今後は記載しませんが、随時ご連絡下さいませ。）